.TH MEM-MONITOR 1 "2008-03-19" "sp-memusage"
.SH NAME
mem-monitor - output system memory usage at given intervals
.SH SYNOPSIS
mem-monitor [interval in secs]
.SH DESCRIPTION
\fImem-monitor\fP outputs (one-liner) system memory usage information from
/proc/meminfo at given intervals.  By default the interval is 3 seconds.
.PP
This is obsoleted by \fImem-cpu-monitor\fP binary which can show also
specified processes memory and CPU usage.
.SH EXAMPLE OUTPUT
Example \fImem-monitor\fP output:
.br
	time:           total:  free:   used:   use-%:  status:
.br
	14:06:26        3220376 2986320 234056  7
.br
	14:06:29        3220376 2986304 234072  7
.SH SEE ALSO
.IR proc (1),
.IR mem-cpu-monitor (1)
.SH COPYRIGHT
Copyright (C) 2007,2008 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
