.TH MEM-SMAPS-PRIVATE 1 "2012-03-13" "sp-memusage"
.SH NAME
mem-smaps-private - show memory usage for given processes
.SH SYNOPSIS
mem-smaps-private \fIPID\fP
.SH DESCRIPTION
\fImem-smaps-private\fP outputs memory usage for the given processes.
This information is parsed mainly from the /proc/PID/smaps file and
includes totals for its memory mappings PSS, clean private and swapped,
private and shared dirty usage.
.SH EXAMPLES
Checking single process memory usage:
.nf
	$ \fImem-smaps-private\fP $(pidof pulseaudio)
	PID 581: pulseaudio --system --high-priority --log-level=0 
	- Swapped dirty memory:       0 kB
	- Private dirty memory:    5776 kB
	- Shared  dirty memory:       0 kB
	- Clean private memory:    2592 kB
	- Proportional set size:   8561 kB
.fi
.PP
Checking all processes memory usage:
.nf
	$ cd /proc
	$ for pid in [0-9]*; do \fImem-smaps-private\fP $pid; done
.fi
.SH SEE ALSO
.IR pmap (1),
.IR mem-cpu-monitor (1),
.IR mem-smaps-totals (1),
.IR mem-dirty-code-pages (1)
.SH COPYRIGHT
Copyright (C) 2006-2012 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
