.TH MEM-SMAPS-PRIVATE 1 "2007-03-26" "sp-memusage"
.SH NAME
mem-smaps-private - show private memory usage of given process
.SH SYNOPSIS
mem-smaps-private \fIPID\fP
.SH DESCRIPTION
\fImem-smaps-private\fP outputs the given process private memory usage.
This information is parsed from the /proc/PID/smaps file.
.SH SEE ALSO
.IR mem-dirty-code-pages (1)
.SH COPYRIGHT
Copyright (C) 2007,2008 Nokia Corporation.
.PP
This is free software.  You may redistribute copies of it under the
terms of the GNU General Public License v2 included with the software.
There is NO WARRANTY, to the extent permitted by law.
