#!/usr/bin/env python

# Copyright (C) 2011 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation. 
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA

import sys, string, re, os, getopt, subprocess, operator


class Options:
	"""
	This class contains options parser implementation.
	"""
	fileIn = None
	fileOut = None

	def parse(argv):
		"Parses the command line arguments and initializes options."
		try:
			opts, args = getopt.gnu_getopt(argv, "i:o:h", 
										["in=", 
										 "out=",
										 "help"])
		except getopt.GetoptError, err:
			print >> sys.stderr, str(err) 
			Options.displayUsage()
			sys.exit(2)
		
		for opt, val in opts:
			if opt == "-i" or opt == "--in":
				Options.fileIn = val
				continue
				
			if opt == "-o" or opt == "--out":
				Options.fileOut = val
				continue
			
			if opt == "-h" or opt == "--help":
				Options.displayUsage()
				sys.exit(0)
				
		return
				

	def displayUsage():
		print \
"""
Usage:
  mem-cpu-plot <options>
  Where <options> are:
	-i <file>  input file.
	-o <file>  output file.
	-h         this help page.
"""

	# static method definitions
	parse = staticmethod(parse)
	displayUsage = staticmethod(displayUsage)


class Unit:
	"""
	This class contains parsed data of single unit - either system
	or process.
	"""
	
	# the unit name
	name = None
	
	def __init__(self, name):
		"""
		"""
		self.name = name
		self.memUsage = []
		self.cpuUsage = []

		
	def appendUsageData(self, mem, cpu):
		"Adds resource (memory, cpu) usage data"
		self.memUsage.append(mem)
		self.cpuUsage.append(cpu)


class Data:
	"""
	This class contains the parsed data
	"""
	
	# Maximum CPU frequency (MHx)
	maxCpu = None
	
	# Total system memory (kB)
	maxMemory = None
	
	# the largest cpu usage in the data set
	topCpu = 0
	
	# the largest memory usage in the data set
	topMemory = 0
	
	def __init__(self):
		self.units = []
		self.time = []
		
		self.units.append(Unit("System"))
		
	def addPlotData(self, timestamp, values):
		"Adds unit resource usage data at the specified timestamp"
		self.time.append(timestamp)
		index = 0
		for unit in self.units:
			if values[index] > self.topMemory:
				self.topMemory = values[index]
			if values[index + 1] > self.topCpu:
				self.topCpu = values[index + 1]
			unit.appendUsageData(values[index], values[index + 1])
			index += 2
			

class Parser:
	"""
	This class parses mem-cpu-monitor output and collects cpu/memory usage data.
	Sample mem-cpu-monitor output:
	  System: CPU: 2201 MHz max, total memory: 4081788 kB RAM, 5099512 kB swap
	  ________ __________________ ___________ _______________________________
	          |  system memory   |system CPU |PID 4402 eclipse               
	     time:|     used: change:|    %: MHz:|  clean:  dirty: change: CPU-%:
	  12:20:00     898992     -92  33.3%  800    14180  164784      +0   0.0%
	  12:20:01     899116    +124   5.9%  828    14176  164788      +4   1.0%
	"""
	
	reSystem = re.compile("System: CPU: ([0-9]+) MHz max, total memory: ([0-9]+) kB RAM, ([0-9]+) kB swap")
	reHeader = re.compile(" *\|  system memory   \|system CPU ")
	reHeaderProcess = re.compile("[^PID]*PID ([0-9]+) ([^\|\n\033]+)")
	reData = re.compile("([^ ]+) +([0-9]+) +[0-9+\-]+ +([0-9\.]+)% +([0-9]+)")
	reTimestamp = re.compile("([0-9]+):([0-9]+):([0-9]+)\.?([0-9]+)?")
	reProcess = re.compile("( *\033[^ ]*m)? *([0-9]+) +([0-9]+) +[0-9+\-]+ +([0-9\.]+)%")


	def __init__(self):
		"""
		"""
	
	
	def adjustCpuFreq(self, perc, freq):
		"""
		Adjust cpu frequency to be percentange of maximu cpu frequency
		instead of current one.
		"""
		if self.data.maxCpu > 0:
			perc = perc * freq / self.data.maxCpu
		return perc


	def readSystemData(self):
		"""
		Reads system data (RAM and swap memory size and maximum CPU frequency:"
		  System: CPU: 2201 MHz max, total memory: 4081788 kB RAM, 5099512 kB swap
		"""
		for line in self.file:
			match = self.reSystem.match(line)
			if match:
				self.data.maxCpu = int(match.group(1))
				self.data.maxMemory = (int(match.group(2)) + int(match.group(3))) * 1024
				return 
		raise RuntimeError("Failed to locate system data")


	def readHeader(self):
		"""
		Reads process header data:
				|  system memory   |system CPU |PID 4402 eclipse			   
		"""
		for line in self.file:
			match = self.reHeader.match(line)
			if match:
				header = line[match.end():]
				while True:
					match = self.reHeaderProcess.match(header)
					if match:
						header = header[match.end():]
						self.data.units.append(Unit("%s(%s)" % (match.group(2).rstrip(), match.group(1))))
					else:
						break
				return 
		raise RuntimeError("Failed to locate system data")
		
	
	def readData(self):
		"""
		Reads resource usage data:
		  12:20:02     899016    -100  16.8%  828    14176  164788      +0   4.7%
		"""
		# skip the first data line, as it contains half initialized values
		for line in self.file:
			match = self.reData.match(line)
			if match:
				break
		
		# parse the rest of data	
		for line in self.file:
			match = self.reData.match(line)
			if match:
				processText = line[match.end():]
				rawTimestamp = match.group(1)
				rawMemoryUsage = match.group(2)
				rawCpuUsage = match.group(3)
				rawCpuFreq = match.group(4)
				match = self.reTimestamp.match(match.group(1))
				timestamp = 0
				if match:
					timestamp = int(match.group(1)) * 3600000 + int(match.group(2)) * 60000 + int(match.group(3)) * 1000
					if match.group(4):
						timestamp += int(match.group(4))
				else:
					raise RuntimeError("Failed to parse timestamp value: %s") % rawTimestamp
				values = []
				values.append(int(rawMemoryUsage))
				values.append(self.adjustCpuFreq(float(rawCpuUsage), int(rawCpuFreq)))
				
				# parse the process data
				while True:
					match = self.reProcess.match(processText)
					if match:
						values.append(int(match.group(3)))
						values.append(self.adjustCpuFreq(float(match.group(4)), int(rawCpuFreq)))
						processText = processText[match.end():]
					else:
						break
				self.data.addPlotData(timestamp, values)
				
	
	def read(self, filename):
		"""
		Reads the specified mem-cpu-monitor output file or standard input if
		the filename was not specified.
		"""
		self.data = Data()
		
		self.file = sys.stdin
		if filename:
			self.file = open(filename, "r")

		self.readSystemData()
		self.readHeader()
		self.readData()
			
		if filename:
			self.file.close()
			
		return self.data
# /class Parser

class Tic:
	"""
	This class provides helper functions for time slices used to represent
	time tics and activity slices.
	"""
	value = 0
	format = None
	text = None
	decimal = 0
		
	def __init__(self, slice, rounded):
		if rounded:
			round = 1
			value = slice
			self.value = 1
			while value != 0:
				self.value = value * round;
				round *= 10
				value /= 10
			#
		else: 
			self.value = slice
			
		self.decimal = 3
		slice = self.value
		while self.decimal and slice and slice % 10 == 0:
			self.decimal -= 1
			slice /= 10	
		self.format = "%%.%df" % self.decimal
	
	def getText(self):
		"Returns tic value converted into text format"
		if not self.text:
			self.text = self.format % (float(self.value) / 1000)
		return self.text	
# /class Tic


class Timestamp:
	"""
	This class provides timestamp utility functions.
	"""
	rxpTimestamp = re.compile("^([0-9]+)\:([0-9]+)\:([0-9]+)\.([0-9]+)$")

	def toString(hours, decimal = 3):
		"Converts integer timestamp (milliseconds since midnight) to text format HH:MM:SS.sss"
		msecs = hours % 1000		
		hours /= 1000
		seconds = hours % 60
		hours /= 60
		minutes = hours % 60
		hours /= 60  
		timestamp = "%02d:%02d:%02d" % (hours, minutes, seconds)
		if decimal > 0:
			for i in range (3 - decimal):
				msecs /= 10
			mask = ".%%0%dd" % decimal
			timestamp += mask % msecs
		return timestamp
	
	toString = staticmethod(toString)
	
	def offsetToString(offset):
		"Converts timestamp offset (milliseconds) to text format +[HH:][MM:][SS][.sss]"
		text = Timestamp.toString(offset)
		text = string.lstrip(text, ":0")
		text = string.rstrip(text, "0")
		if text[-1] == '.':
			text = string.rstrip(text, ".")
		if text == "" or text[0] == '.':
			text = "0" + text
		return text
	
	offsetToString = staticmethod(offsetToString)
	
	def fromString(text):
		"Converts text format timestamp HH:MM:SS.sss into integer value (milliseconds since midnight)"
		timestamp = 0
		match = Timestamp.rxpTimestamp.match(text)
		if match:
			timestamp = int(match.group(1)) * 3600000 + int(match.group(2)) * 60000 + int(match.group(3)) * 1000 + int(match.group(4))
		return timestamp

	fromString = staticmethod(fromString)
# /class Timestamp


class Plotter:
	"""
	Creates gnuplot configuration/data files and invokes gnuplot to create
	the graphs.
	"""	
	DataFilename = "mem-cpu-usage.dat"
	ConfigFilename = "mem-cpu-usage.cfg"
	
	def __init__(self, title):
		"""
		"""
		self.title = title
		
		
	def createDataFile(self, name, data):
		"""
		Create gnuplot data file:
		  <timestamp> <system mem> <system cpu> <proc1 mem> <proc1 cpu> <proc2 mem> <proc2 cpu> ...
		  ...
		"""
		file = open(name, "w")
		if file is None:
			raise RuntimeError("Failed to create data file: %s" % name)
		index = 0
		for timestamp in data.time:
			file.write("%d" % timestamp)
			for unit in data.units:
				file.write(" %d %f" % (unit.memUsage[index], unit.cpuUsage[index]))
			index += 1
			file.write("\n")
		file.close()
		
		
	def removeFile(self, name):
		"Removes the specified file."
		if os.path.isfile(name):
			os.remove(name)
		
		
	def setAxisY(self, label, min, max, format = None):
		"Sets Y axis range (min-max) and formatting."
		if min == max:
			max += 1
		self.cfg.write("set yrange[%d:%d]\n" % (min, max))
		
		if format:
			self.cfg.write("set format y \"%s\"\n" % format)
		self.cfg.write("set ytics out\n")
		
		self.cfg.write("set ylabel \"%s\"\n" % label)
	
	
	def setAxisY2(self, label, min, max, format = None):
		"Sets Y2 axis range and formatting."
		
		self.cfg.write("set y2range[%d:%d]\n" % (min, max))
		
		if format:
			self.cfg.write("set format y2 \"%s\"\n" % format)
		self.cfg.write("set y2tics out\n")
		self.cfg.write("set ytics nomirror\n")
		
		self.cfg.write("set y2label \"%s\"\n" % label)

	def setAxisX(self, label, min = None, max = None, format = None, scale = None):
		"Sets X axis range (min-max) and formatting."

		# set ticks
		self.cfg.write("set xtics rotate nomirror\n")
		if scale:
			self.cfg.write("set xtics scale %s\n" % scale)
			
		if min:
			if min == max:
				max += 1
			range = max - min
			step = Tic(range / 10, True)
			tic = min - min % step.value
			if min % step.value > 0:
				tic += step.value
			min = tic
			
			# set label
			self.cfg.write("set xlabel \"%s\" offset 0,0\n" % label)
			# set  range
			self.cfg.write("set xrange[%d:%d]\n" % (min, max))
			# set the X axis tic label format, not used as tics are printed manually
	
			# place autotics outside range to avoid interference with manual tics
			self.cfg.write("set xtics %f,%f\n" % (max * 2, max * 2))
			
			while tic <= max - step.value:
				self.cfg.write("set xtics add (\"%s\\n+%s\" %d)\n" % (Timestamp.toString(tic, step.decimal), Timestamp.offsetToString(tic - min), tic))
				tic += step.value
			self.cfg.write("set xtics add (\"%s\\n+%s\" %d)\n" % (Timestamp.toString(max), Timestamp.offsetToString(range), max))
			

	def setHeader(self):
		"Sets the configuration file header."
		self.cfg.write("set terminal svg size 1024,768 dynamic\n")
		self.cfg.write("set title \"%s\"\n" % self.title)
		self.cfg.write("set style data lines\n")
		self.cfg.write("set key bmargin\n")
		
	def setPlot(self):
		"Sets the graphs for system and process resource usage."
		self.cfg.write("plot \\\n")
		index = 2
		for unit in data.units:
			if index > 2:
				self.cfg.write("\\\n\t,")
			else:
				self.cfg.write("\t")
			self.cfg.write("\"%s\" using 1:%d title \"%s(memory)\" axes x1y1 \\\n" % (self.DataFilename, index, unit.name))
			self.cfg.write("\t,\"%s\" using 1:%d title \"%s(cpu)\" axes x1y2" % (self.DataFilename, index + 1, unit.name))
			index += 2
		self.cfg.write("\n")

	def createConfigFile(self, name, data):
		"Creates gnuplot configuration file."
		self.cfg = open(name, "w")
		if self.cfg is None:
			raise RuntimeError("Failed to create data file: %s" % name)
		
		self.setHeader()
		self.setAxisX("Time (s)", data.time[0], data.time[-1])
		self.setAxisY("Memory", 0, data.topMemory * 1.1, "%.1s%c")
		self.setAxisY2("CPU %", 0, data.topCpu * 1.1)
		self.setPlot()
		
		self.cfg.close()
		
	def cleanup(self):
		"Removes gnuplot configuration and data files."
		self.removeFile(self.DataFilename)
		self.removeFile(self.ConfigFilename)
		
	def plot(self, data):
		"Plot the resource usage graphs from the specified data"
		# prepare configuration and data files
		self.createConfigFile(self.ConfigFilename, data)
		self.createDataFile(self.DataFilename, data)
		
		# Convert with gnuplot
		try:
			file = None
			if Options.fileOut:
				file = open(Options.fileOut, "w")
				if file is None:
					raise RuntimeError("Failed to create output file: %s" % Options.fileOut)
			
			gnuplot = subprocess.Popen(["gnuplot", self.ConfigFilename], 0, None, None, file or sys.stdout)
			gnuplot.wait()
			if file:
				file.close()
		except OSError, e:
			print >> sys.stderr, "ERROR: failed to execute gnuplot (%s)" % e.strerror
			print >> sys.stderr, "Check if the gnuplot is installed and try again."
			self.cleanup()
			sys.exit(2)
				
		# remove demporary data files
		self.cleanup()
		 

# main

Options.parse(sys.argv[1:])
parser = Parser()
data = parser.read(Options.fileIn)
plotter = Plotter("Memory and CPU usage graph")
plotter.plot(data)


