#!/bin/sh
#
# Script for calculating memory usage for given process PIDs.
# This file is part of sp-memusage.
#
# Copyright (C) 2006-2012 by Nokia Corporation
#
# Contact: Eero Tamminen <eero.tamminen@nokia.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation. 
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA

if [ $# -lt 1 ]; then
	echo
	echo "usage: ${0##*/} <process PIDs or names>"
	echo
	echo "print the process(es) resource usage according to SMAPS etc."
	echo
	echo "examples:"
	echo "  ${0##*/} pulseaudio"
	echo "or:"
	echo "  cd /proc"
	echo "  ${0##*/} [0-9]*"
	echo
	exit 1
fi

cd /proc
if [ -f self/oom_score_adj ]; then
	oom_adj=oom_score_adj
else
	oom_adj=oom_adj
fi

output_pid_info()
{
	smaps=$1/smaps
	if [ \! -f $smaps ]; then
		echo "ERROR: $smaps SMAPS file doesn't exist!"
		return
	fi
	cmd=$(tr '\0' ' ' < $1/cmdline)
	if [ -z "$cmd" ]; then
		echo "PID $1 is a kernel thread"
		return
	fi
	bin=${cmd%% *}
	opt=${cmd#* }
	echo "PID $1: ${bin##*/} $opt"
	echo "- FD count: $(ls $1/fd|wc -l)"
	echo "- OOM score: $(cat $1/oom_score) (adj=$(cat $1/$oom_adj))"
	awk '
/^Swap:/	  { swap   += $2; next }
/^Private_Dirty:/ { pdirty += $2; next }
/^Shared_Dirty:/  { sdirty += $2; next }
/^Private_Clean:/ { pclean += $2; next }
/^Pss:/		  { pss    += $2; next }
END {
	printf("- Swapped dirty memory:  %6d kB\n", swap);
	printf("- Private dirty memory:  %6d kB\n", pdirty);
	printf("- Shared  dirty memory:  %6d kB\n", sdirty);
	printf("- Clean private memory:  %6d kB\n", pclean);
	printf("- Proportional set size: %6d kB\n", pss);
}' $smaps
	awk '
/^VmPeak:/ { peak = $2; next }
/^VmSize:/ { size = $2; next }
END {
	printf("- Virtual size (peak):   %6d kB (%d kB)\n", size, peak);
}' $1/status
	echo "- Thread IDs: $(ls $1/task|tr '\n' ' ')"
}

for pid in $*; do
	if [ -d $pid ]; then
		output_pid_info $pid
		continue
	fi
	# not a numeric PID, was it a process name?
	pids=$(pidof $pid)
	if [ -z "$pids" ]; then
		echo "ERROR: PID $pid doesn't exist!"
		continue
	fi
	for pid in $pids; do
		if [ -d $pid ]; then
			output_pid_info $pid
		fi
	done
done
